baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'toha'

enableEmoji = true

[logo]
	main = "images/site/logo_de_3_.png"
	inverted = "images/site/logo_de_4_.png"
	favicon = "images/site/logo_de_4_.png"

[languages.en]
languageName = "English"
weight = 1

[languages.fr]
languageName = "French"
weight = 2

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false

[params]
gitRepo = "https://github.com/hugo-toha/hugo-toha.github.io"
enableBlogPost = true
enableTOC = true
background ="images/site/background.jpg"

  [params.newsletter]
  enable = false
